name: farm_link
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.1
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.5.1
  intl: ^0.19.0
  flutter_svg: ^2.0.10
  image_picker: ^1.1.1
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  connectivity_plus: ^6.1.4
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.8.1
  get_it: ^7.6.4
  cloudinary_flutter: ^1.0.0
  cloudinary_url_gen: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env